-- Drop all tables
-- MUst be done in correct order.

DROP TABLE IF EXIST TAGS_XREF CASCADE;
DROP TABLE IF EXIST TAGS CASCADE;

DROP TABLE IF EXIST COMPOSITE CASCADE;
DROP TABLE IF EXIST IMAGES CASCADE;

